import './globals.css'
import { Rubik } from "next/font/google";

const inter = Rubik({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: 'Bubu Dudu Shopping List',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
